# env:
#   SEMGREP_REPO_URL  : https://github.com/s-santillan/DjangoGoat
#   SEMGREP_BRANCH    : master
#   SEMGREP_REPO_NAME : DjangoGoat
#   SEMGREP_COMMIT    : 7501714231bfead242a714672ad666b01af1d07
on:
  pull_request: {}
  push:
    branches:
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  - cron: '0 0 * * 0'
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      SEMGREP_REPO_URL  : https://github.com/s-santillan/DjangoGoat
      SEMGREP_BRANCH    : master
      SEMGREP_REPO_NAME : DjangoGoat
      SEMGREP_COMMIT    : 7501714231bfead242a714672ad666b01af1d07
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci --sarif --output=test13.sarif
